package ec;

import java.util.ArrayList;

public class Driver {	
	ArrayList<Integer> list33 = new ArrayList<Integer>();
	static ArrayList<Integer> count = new ArrayList<Integer>();
	
	static BubbleSort<Integer> bs = new BubbleSort<Integer>();
	static SelectionSort<Integer> sc = new SelectionSort<Integer>();
	static InsertionSort<Integer> ins = new InsertionSort<Integer>();
	static QuickSort<Integer> qui = new QuickSort<Integer>();
	static MergeSort<Integer> mer = new MergeSort<Integer>();
	static CockTailSort<Integer> cock = new CockTailSort<Integer>();
	static GnomeSort<Integer> gno = new GnomeSort<Integer>();
	static RadixSort<Integer> rad = new RadixSort<Integer>();
	static CountingSort<Integer> coun = new CountingSort<Integer>();
	
	public static void print10List() {		
		ArrayList<Integer> list1 = new ArrayList<Integer>();
		
		System.out.println("BUBBLE SORT:\t\t\t SELECTION SORT:\t\t  INSERTION SORT:\t\t   QUICK SORT:\t\t\t    MERGE SORT:\t\t\t"
				+ "     COCKTAIL SORT:\t\t      GNOME SORT:\t\t       RADIX SORT:\t\t\tCOUNTING SORT:");
		System.out.println();
		RandomIntegers.randomizeList10(list1);
		ArrayList<Integer> bubble10 = bs.print(list1);
		ArrayList<Integer> selection10 = sc.print(list1);
		ArrayList<Integer> insertion10 = ins.print(list1);
		ArrayList<Integer> quick10 = qui.print(list1);
		ArrayList<Integer> merge10 = mer.print(list1);
		ArrayList<Integer> cocktail10 = cock.print(list1);
		ArrayList<Integer> gnome10 = gno.print(list1);
		ArrayList<Integer> radix10 = rad.print(list1);
		ArrayList<Integer> count10 = coun.print(list1);
		int[] count0 = new int[count10.size()];
		for (int i = 0; i < count0.length; i++) {
			count0[i] = count10.get(i);
		}bs.bubbleSort(count10);

		System.out.println("List of 10 random numbers:\t List of 10 random numbers:\t  List of 10 random numbers:\t   List of 10 random numbers:\t "
				+ "   List of 10 random numbers:\t     List of 10 random numbers:       List of 10 random numbers:     "
				+ "  List of 10 random numbers:\tList of 10 random numbers: ");
		Print.printList10(bubble10);
		System.out.printf("\t\t ");
		Print.printList10(selection10);
		System.out.printf("\t\t  ");
		Print.printList10(insertion10);
		System.out.printf("\t\t   ");
		Print.printList10(quick10);
		System.out.printf("\t\t    ");
		Print.printList10(merge10);
		System.out.printf("\t     ");
		Print.printList10(cocktail10);
		System.out.printf("             ");
		Print.printList10(gnome10);
		System.out.printf("\t       ");
		Print.printList10(radix10);
		System.out.printf("\t\t");
		Print.printList10(list1);
		
		System.out.printf("");
		System.out.println();
		System.out.println();
		
		bs.bubbleSort(bubble10);
		sc.selectionSort(selection10);
		ins.insertionSort(insertion10);
		qui.quickSort4(quick10);
		mer.mergeSort3(merge10);
		cock.cockTailSort(cocktail10);
		gno.gnomeSort(gnome10);
		rad.radixSort(radix10);
		coun.countingSort(count0);
		
		System.out.println("Bubble sorted list:\t\t Selection sorted list:\t\t  Insertion Sorted list:\t"
				+ "   Quick Sorted list:\t\t    Merge Sorted list:\t\t     Cocktail Sorted list:\t"
				+ "      Gnome Sorted list:\t       Radix Sorted list:\t\tCounting Sorted list:"); 
		Print.printList10(bubble10);
		System.out.printf("\t\t ");
		Print.printList10(selection10);
		System.out.printf("\t\t  ");
		Print.printList10(insertion10);
		System.out.printf("\t\t   ");
		Print.printList10(quick10);
		System.out.printf("\t\t    ");
		Print.printList10(merge10);
		System.out.printf("\t     ");
		Print.printList10(cocktail10);
		System.out.printf("\t      ");
		Print.printList10(gnome10);
		System.out.printf("\t       ");
		Print.printList10(radix10);
		System.out.printf("\t\t");
		Print.printList10(count10);
		
		System.out.printf("");
		System.out.println();
		System.out.println();
		
		bs.compare();
		System.out.printf("\t ");
		sc.compare();
		System.out.printf("\t\t  ");
		ins.compare();
		System.out.printf("\t\t   ");
		QuickSort.compare();
		System.out.printf("\t\t    ");
		MergeSort.compare();
		System.out.printf("\t\t     ");
		CockTailSort.compare();
		System.out.printf("\t      ");
		GnomeSort.compare();
		System.out.printf("\t       ");
		RadixSort.runtime();
		System.out.printf("\t\t\t");
		CountingSort.runtime();
		System.out.println();
		
		bs.swap();
		System.out.printf("\t\t\t ");
		sc.swap();
		System.out.printf("\t\t\t  ");
		ins.swap();
		System.out.printf("\t\t\t   ");
		QuickSort.swap();
		System.out.printf("\t\t\t    ");
		MergeSort.swap();
		System.out.printf("\t\t\t     ");
		CockTailSort.swap();
		System.out.printf("\t\t\t      ");
		GnomeSort.swap();
		System.out.printf("\t\t\t  ");
		System.out.println();
		
		bs.runtime();
		System.out.printf("\t\t\t ");
		sc.runtime();
		System.out.printf("\t\t\t  ");
		ins.runtime();
		System.out.printf("\t\t\t   ");
		qui.runtime();
		System.out.printf("\t\t    ");
		MergeSort.runtime();
		System.out.printf("\t\t     ");
		CockTailSort.runtime();
		System.out.printf("\t\t      ");
		GnomeSort.runtime();
		
		System.out.printf("\t\t\t  ");
		System.out.println();
		System.out.println();
	}
	
	public static void print100List() { 
		ArrayList<Integer> list8 = new ArrayList<Integer>();
		RandomIntegers.randomizeList100(list8);
		
		ArrayList<Integer> bubble100 = bs.print(list8);
		ArrayList<Integer> selection100 = sc.print(list8);
		ArrayList<Integer> insertion100 = ins.print(list8);
		ArrayList<Integer> quick100 = qui.print(list8);
		ArrayList<Integer> merge100 = mer.print(list8);
		ArrayList<Integer> cocktail100 = cock.print(list8);
		ArrayList<Integer> gnome100 = gno.print(list8);
		ArrayList<Integer> radix100 = rad.print(list8);
		ArrayList<Integer> count100 = coun.print(list8);
		
		int[] count00 = new int[count100.size()];
		for (int i = 0; i < count00.length; i++) {
			count00[i] = count100.get(i);
		}

		System.out.println("List of 100 random numbers:\t List of 100 random numbers:\t  List of 100 random numbers:\t "
				+ "  List of 100 random numbers:\t    List of 100 random numbers:\t     List of 100 random numbers:     "
				+ " List of 100 random numbers:      List of 100 random numbers:      List of 100 random numbers:");
		
		ArrayList<Integer> bublistp1 = new ArrayList<Integer>(bubble100.subList(0, 10));
		String deleteString1 = bublistp1.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString1 + "\t ");
		ArrayList<Integer> selclistp1 = new ArrayList<Integer>(selection100.subList(0, 10));
		String deleteString2 = selclistp1.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString2 + "\t  ");
		ArrayList<Integer> inslistp1 = new ArrayList<Integer>(insertion100.subList(0, 10));
		String deleteString3 = inslistp1.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString3 + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp1 = new ArrayList<Integer>(quick100.subList(0, 10));
		String deleteString16 = qlistp1.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString16 + "    ");
		ArrayList<Integer> merglistp1 = new ArrayList<Integer>(merge100.subList(0, 10));
		String deleteString17 = merglistp1.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString17 + "    ");
		ArrayList<Integer> cocklistp1 = new ArrayList<Integer>(cocktail100.subList(0, 10));
		String deleteString19 = cocklistp1.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString19 + "    ");
		ArrayList<Integer> gnomlistp1 = new ArrayList<Integer>(gnome100.subList(0, 10));
		String deleteString20 = gnomlistp1.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString20 + "    ");
		ArrayList<Integer> radlistp1 = new ArrayList<Integer>(radix100.subList(0, 10));
		String deleteString18 = radlistp1.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString18 + "    ");
		ArrayList<Integer> coulistp1 = new ArrayList<Integer>(count100.subList(0, 10));
		String deleteString101 = coulistp1.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString101 + "");
		System.out.println();

		ArrayList<Integer> bublistp2 = new ArrayList<Integer>(bubble100.subList(10, 20));
		String deleteString4 = bublistp2.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString4 + "\t ");
		ArrayList<Integer> selclistp2 = new ArrayList<Integer>(selection100.subList(10, 20));
		String deleteString5 = selclistp2.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString5 + "\t  ");
		ArrayList<Integer> inslistp2 = new ArrayList<Integer>(insertion100.subList(10, 20));
		String deleteString6 = inslistp2.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString6 + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp2 = new ArrayList<Integer>(quick100.subList(10, 20));
		String deleteString21 = qlistp2.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString21 + "    ");
		ArrayList<Integer> merglistp2 = new ArrayList<Integer>(merge100.subList(10, 20));
		String deleteString22 = merglistp2.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString22 + "    ");
		ArrayList<Integer> cocklistp2 = new ArrayList<Integer>(cocktail100.subList(10, 20));
		String deleteString24 = cocklistp2.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString24 + "    ");
		ArrayList<Integer> gnomlistp2 = new ArrayList<Integer>(gnome100.subList(10, 20));
		String deleteString25 = gnomlistp2.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString25 + "    ");
		ArrayList<Integer> radlistp2 = new ArrayList<Integer>(radix100.subList(10, 20));
		String deleteString23 = radlistp2.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString23 + "    ");
		ArrayList<Integer> coulistp2 = new ArrayList<Integer>(count100.subList(10, 20));
		String deleteString102 = coulistp2.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString102 + "");
		System.out.println();

		ArrayList<Integer> bublistp3 = new ArrayList<Integer>(bubble100.subList(20, 30));
		String deleteString7 = bublistp3.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString7 + "\t ");
		ArrayList<Integer> selclistp3 = new ArrayList<Integer>(selection100.subList(20, 30));
		String deleteString8 = selclistp3.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString8+ "\t  ");
		ArrayList<Integer> inslistp3 = new ArrayList<Integer>(insertion100.subList(20, 30));
		String deleteString9 = inslistp3.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString9 + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp3 = new ArrayList<Integer>(quick100.subList(20, 30));
		String deleteString26 = qlistp3.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString26 + "    ");
		ArrayList<Integer> merglistp3 = new ArrayList<Integer>(merge100.subList(20, 30));
		String deleteString27 = merglistp3.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString27 + "    ");
		ArrayList<Integer> cocklistp3 = new ArrayList<Integer>(cocktail100.subList(20, 30));
		String deleteString29 = cocklistp3.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString29 + "    ");
		ArrayList<Integer> gnomlistp3 = new ArrayList<Integer>(gnome100.subList(20, 30));
		String deleteString30 = gnomlistp3.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString30 + "    ");
		ArrayList<Integer> radlistp3 = new ArrayList<Integer>(radix100.subList(20, 30));
		String deleteString28 = radlistp3.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString28 + "    ");
		ArrayList<Integer> coulistp3 = new ArrayList<Integer>(count100.subList(20, 30));
		String deleteString103 = coulistp3.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString103 + "");
		System.out.println();

		ArrayList<Integer> bublistp4 = new ArrayList<Integer>(bubble100.subList(30, 40));
		String deleteString10 = bublistp4.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString10 + "\t ");
		ArrayList<Integer> selclistp4 = new ArrayList<Integer>(selection100.subList(30, 40));
		String deleteString11 = selclistp4.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString11 + "\t  ");
		ArrayList<Integer> inslistp4 = new ArrayList<Integer>(insertion100.subList(30, 40));
		String deleteString12 = inslistp4.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString12 + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp4 = new ArrayList<Integer>(quick100.subList(30, 40));
		String deleteString31 = qlistp4.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString31 + "    ");
		ArrayList<Integer> merglistp4 = new ArrayList<Integer>(merge100.subList(30, 40));
		String deleteString32 = merglistp4.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString32 + "    ");
		ArrayList<Integer> cocklistp4 = new ArrayList<Integer>(cocktail100.subList(30, 40));
		String deleteString34 = cocklistp4.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString34 + "    ");
		ArrayList<Integer> gnomlistp4 = new ArrayList<Integer>(gnome100.subList(30, 40));
		String deleteString35 = gnomlistp4.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString35 + "    ");
		ArrayList<Integer> radlistp4 = new ArrayList<Integer>(radix100.subList(30, 40));
		String deleteString33 = radlistp4.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString33 + "    ");
		ArrayList<Integer> coulistp4 = new ArrayList<Integer>(count100.subList(30, 40));
		String deleteString104 = coulistp4.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString104 + "");
		System.out.println();

		ArrayList<Integer> bublistp5 = new ArrayList<Integer>(bubble100.subList(40, 50));
		String deleteString13 = bublistp5.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString13 + "\t ");
		ArrayList<Integer> selclistp5 = new ArrayList<Integer>(selection100.subList(40, 50));
		String deleteString14 = selclistp5.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString14 + "\t  ");
		ArrayList<Integer> inslistp5 = new ArrayList<Integer>(insertion100.subList(40, 50));
		String deleteString15 = inslistp5.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString15 + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp5 = new ArrayList<Integer>(quick100.subList(40, 50));
		String deleteString36 = qlistp5.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString36 + "    ");
		ArrayList<Integer> merglistp5 = new ArrayList<Integer>(merge100.subList(40, 50));
		String deleteString37 = merglistp5.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString37 + "    ");
		ArrayList<Integer> cocklistp5 = new ArrayList<Integer>(cocktail100.subList(40, 50));
		String deleteString39 = cocklistp5.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString39 + "    ");
		ArrayList<Integer> gnomlistp5 = new ArrayList<Integer>(gnome100.subList(40, 50));
		String deleteString40 = gnomlistp5.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString40 + "    ");
		ArrayList<Integer> radlistp5 = new ArrayList<Integer>(radix100.subList(40, 50));
		String deleteString38 = radlistp5.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString38 + "    ");
		ArrayList<Integer> coulistp5 = new ArrayList<Integer>(count100.subList(40, 50));
		String deleteString105 = coulistp5.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString105 + "");
		System.out.println();

		ArrayList<Integer> bublistp6 = new ArrayList<Integer>(bubble100.subList(50, 60));
		String deleteString41 = bublistp6.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString41 + "\t ");
		ArrayList<Integer> selclistp6 = new ArrayList<Integer>(selection100.subList(50, 60));
		String deleteString42 = selclistp6.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString42 + "\t  ");
		ArrayList<Integer> inslistp6 = new ArrayList<Integer>(insertion100.subList(50, 60));
		String deleteString43 = inslistp6.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString43 + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp6 = new ArrayList<Integer>(quick100.subList(50, 60));
		String deleteString44 = qlistp6.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString44 + "    ");
		ArrayList<Integer> merglistp6 = new ArrayList<Integer>(merge100.subList(50, 60));
		String deleteString45 = merglistp6.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString45 + "    ");
		ArrayList<Integer> cocklistp6 = new ArrayList<Integer>(cocktail100.subList(50, 60));
		String deleteString47 = cocklistp6.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString47 + "    ");
		ArrayList<Integer> gnomlistp6 = new ArrayList<Integer>(gnome100.subList(50, 60));
		String deleteString48 = gnomlistp6.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString48 + "    ");
		ArrayList<Integer> radlistp6 = new ArrayList<Integer>(radix100.subList(50, 60));
		String deleteString46 = radlistp6.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString46 + "    ");
		ArrayList<Integer> coulistp6 = new ArrayList<Integer>(count100.subList(50, 60));
		String deleteString106 = coulistp6.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString106 + "");
		System.out.println();

		ArrayList<Integer> bublistp7 = new ArrayList<Integer>(bubble100.subList(60, 70));
		String deleteString49 = bublistp7.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString49 + "\t ");
		ArrayList<Integer> selclistp7 = new ArrayList<Integer>(selection100.subList(60, 70));
		String deleteString50 = selclistp7.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString50 + "\t  ");
		ArrayList<Integer> inslistp7 = new ArrayList<Integer>(insertion100.subList(60, 70));
		String deleteString51 = inslistp7.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString51 + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp7 = new ArrayList<Integer>(quick100.subList(60, 70));
		String deleteString52 = qlistp7.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString52 + "    ");
		ArrayList<Integer> merglistp7 = new ArrayList<Integer>(merge100.subList(60, 70));
		String deleteString53 = merglistp7.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString53 + "    ");
		ArrayList<Integer> cocklistp7 = new ArrayList<Integer>(cocktail100.subList(60, 70));
		String deleteString55 = cocklistp7.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString55 + "    ");
		ArrayList<Integer> gnomlistp7 = new ArrayList<Integer>(gnome100.subList(60, 70));
		String deleteString56 = gnomlistp7.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString56 + "    ");
		ArrayList<Integer> radlistp7 = new ArrayList<Integer>(radix100.subList(60, 70));
		String deleteString54 = radlistp7.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString54 + "    ");
		ArrayList<Integer> coulistp7 = new ArrayList<Integer>(count100.subList(60, 70));
		String deleteString107 = coulistp7.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString107 + "");
		System.out.println();

		ArrayList<Integer> bublistp8 = new ArrayList<Integer>(bubble100.subList(70, 80));
		String deleteString57 = bublistp8.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString57 + "\t ");
		ArrayList<Integer> selclistp8 = new ArrayList<Integer>(selection100.subList(70, 80));
		String deleteString58 = selclistp8.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString58 + "\t  ");
		bs.bubbleSort(count100);
		ArrayList<Integer> inslistp8 = new ArrayList<Integer>(insertion100.subList(70, 80));
		String deleteString59 = inslistp8.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString59 + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp8 = new ArrayList<Integer>(quick100.subList(70, 80));
		String deleteString60 = qlistp8.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString60 + "    ");
		ArrayList<Integer> merglistp8 = new ArrayList<Integer>(merge100.subList(70, 80));
		String deleteString61 = merglistp8.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString61 + "    ");
		ArrayList<Integer> cocklistp8 = new ArrayList<Integer>(cocktail100.subList(70, 80));
		String deleteString63 = cocklistp8.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString63 + "    ");
		ArrayList<Integer> gnomlistp8 = new ArrayList<Integer>(gnome100.subList(70, 80));
		String deleteString64 = gnomlistp8.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString64 + "    ");
		ArrayList<Integer> radlistp8 = new ArrayList<Integer>(radix100.subList(70, 80));
		String deleteString62 = radlistp8.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString62 + "    ");
		ArrayList<Integer> coulistp7a = new ArrayList<Integer>(cocktail100.subList(70, 80));
		String deleteString107a = coulistp7a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString107a + "");
		System.out.println();

		ArrayList<Integer> bublistp9 = new ArrayList<Integer>(bubble100.subList(80, 90));
		String deleteString65 = bublistp9.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString65 + "\t ");
		ArrayList<Integer> selclistp9 = new ArrayList<Integer>(selection100.subList(80, 90));
		String deleteString66 = selclistp9.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString66 + "\t  ");
		ArrayList<Integer> inslistp9 = new ArrayList<Integer>(insertion100.subList(80, 90));
		String deleteString67 = inslistp9.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString67 + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp9 = new ArrayList<Integer>(quick100.subList(80, 90));
		String deleteString68 = qlistp9.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString68 + "    ");
		ArrayList<Integer> merglistp9 = new ArrayList<Integer>(merge100.subList(80, 90));
		String deleteString69 = merglistp9.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString69 + "    ");
		ArrayList<Integer> cocklistp9 = new ArrayList<Integer>(cocktail100.subList(80, 90));
		String deleteString71 = cocklistp9.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString71 + "    ");
		ArrayList<Integer> gnomlistp9 = new ArrayList<Integer>(gnome100.subList(80, 90));
		String deleteString72 = gnomlistp9.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString72 + "    ");
		ArrayList<Integer> radlistp9 = new ArrayList<Integer>(radix100.subList(80, 90));
		String deleteString70 = radlistp9.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString70 + "    ");
		ArrayList<Integer> coulistp7b = new ArrayList<Integer>(insertion100.subList(80, 90));
		String deleteString107b = coulistp7b.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString107b + "");
		System.out.println();

		ArrayList<Integer> bublistp10 = new ArrayList<Integer>(bubble100.subList(90, 100));
		String deleteString73 = bublistp10.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString73 + "\t ");
		ArrayList<Integer> selclistp10 = new ArrayList<Integer>(selection100.subList(90, 100));
		String deleteString74 = selclistp10.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString74 + "\t  ");
		ArrayList<Integer> inslistp10 = new ArrayList<Integer>(insertion100.subList(90, 100));
		String deleteString75 = inslistp10.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString75 + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp10 = new ArrayList<Integer>(quick100.subList(90, 100));
		String deleteString76 = qlistp10.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString76 + "    ");
		ArrayList<Integer> merglistp10 = new ArrayList<Integer>(merge100.subList(90, 100));
		String deleteString77 = merglistp10.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString77 + "    ");
		ArrayList<Integer> cocklistp10 = new ArrayList<Integer>(cocktail100.subList(90, 100));
		String deleteString79 = cocklistp10.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString79 + "    ");
		ArrayList<Integer> gnomlistp10 = new ArrayList<Integer>(gnome100.subList(90, 100));
		String deleteString80 = gnomlistp10.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString80 + "    ");
		ArrayList<Integer> radlistp10 = new ArrayList<Integer>(radix100.subList(90, 100));
		String deleteString78 = radlistp10.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString78 + "    ");
		ArrayList<Integer> coulistp7c = new ArrayList<Integer>(cocktail100.subList(90, 100));
		String deleteString107c = coulistp7c.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString107c + "");
		System.out.println();
		System.out.println();

		bs.bubbleSort(bubble100);
		sc.selectionSort(selection100);
		ins.insertionSort(insertion100);
		qui.quickSort4(quick100);
		mer.mergeSort3(merge100);
		cock.cockTailSort(cocktail100);
		gno.gnomeSort(gnome100);
		rad.radixSort(radix100);
		coun.countingSort(count00);
		
		System.out.println("Bubble sorted list:\t\t Selection sorted list:\t\t  Insertion Sorted list:\t   Quick Sorted list:\t\t    Merge Sorted list:\t\t     Cocktail Sorted list:\t      Gnome Sorted list:\t       Radix Sorted list:\t\tCounting Sorted list:");

		ArrayList<Integer> bublistp1a = new ArrayList<Integer>(bubble100.subList(0, 10));
		String deleteString1a = bublistp1a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString1a + "\t ");
		ArrayList<Integer> selclistp1a = new ArrayList<Integer>(selection100.subList(0, 10));
		String deleteString2a = selclistp1a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString2a + "\t  ");
		ArrayList<Integer> inslistp1a = new ArrayList<Integer>(insertion100.subList(0, 10));
		String deleteString3a = inslistp1a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString3a + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp1a = new ArrayList<Integer>(quick100.subList(0, 10));
		String deleteString16a = qlistp1a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString16a + "    ");
		ArrayList<Integer> merglistp1a = new ArrayList<Integer>(merge100.subList(0, 10));
		String deleteString17a = merglistp1a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString17a + "    ");
		ArrayList<Integer> cocklistp1a = new ArrayList<Integer>(cocktail100.subList(0, 10));
		String deleteString19a = cocklistp1a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString19a + "    ");
		ArrayList<Integer> gnomlistp1a = new ArrayList<Integer>(gnome100.subList(0, 10));
		String deleteString20a = gnomlistp1a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString20a + "    ");
		ArrayList<Integer> radlistp1a = new ArrayList<Integer>(radix100.subList(0, 10));
		String deleteString18a = radlistp1a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString18a + "    ");
		ArrayList<Integer> coulistp11 = new ArrayList<Integer>(count100.subList(0, 10));
		String deleteString111 = coulistp11.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString111 + "");
		System.out.println();

		ArrayList<Integer> bublistp2a = new ArrayList<Integer>(bubble100.subList(10, 20));
		String deleteString4a = bublistp2a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString4a + "\t ");
		ArrayList<Integer> selclistp2a = new ArrayList<Integer>(selection100.subList(10, 20));
		String deleteString5a = selclistp2a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString5a + "\t  ");
		ArrayList<Integer> inslistp2a = new ArrayList<Integer>(insertion100.subList(10, 20));
		String deleteString6a = inslistp2a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString6a + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp2a = new ArrayList<Integer>(quick100.subList(10, 20));
		String deleteString21a = qlistp2a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString21a + "    ");
		ArrayList<Integer> merglistp2a = new ArrayList<Integer>(merge100.subList(10, 20));
		String deleteString22a = merglistp2a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString22a + "    ");
		ArrayList<Integer> cocklistp2a = new ArrayList<Integer>(cocktail100.subList(10, 20));
		String deleteString24a = cocklistp2a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString24a + "    ");
		ArrayList<Integer> gnomlistp2a = new ArrayList<Integer>(gnome100.subList(10, 20));
		String deleteString25a = gnomlistp2a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString25a + "    ");
		ArrayList<Integer> radlistp2a = new ArrayList<Integer>(radix100.subList(10, 20));
		String deleteString23a = radlistp2a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString23a + "    ");
		ArrayList<Integer> coulistp12 = new ArrayList<Integer>(count100.subList(10, 20));
		String deleteString112 = coulistp12.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString112 + "");
		System.out.println();

		ArrayList<Integer> bublistp3a = new ArrayList<Integer>(bubble100.subList(20, 30));
		String deleteString7a = bublistp3a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString7a + "\t ");
		ArrayList<Integer> selclistp3a = new ArrayList<Integer>(selection100.subList(20, 30));
		String deleteString8a = selclistp3a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString8a + "\t  ");
		ArrayList<Integer> inslistp3a = new ArrayList<Integer>(insertion100.subList(20, 30));
		String deleteString9a = inslistp3a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString9a + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp3a = new ArrayList<Integer>(quick100.subList(20, 30));
		String deleteString26a = qlistp3a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString26a + "    ");
		ArrayList<Integer> merglistp3a = new ArrayList<Integer>(merge100.subList(20, 30));
		String deleteString27a = merglistp3a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString27a + "    ");
		ArrayList<Integer> cocklistp3a = new ArrayList<Integer>(cocktail100.subList(20, 30));
		String deleteString29a = cocklistp3a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString29a + "    ");
		ArrayList<Integer> gnomlistp3a = new ArrayList<Integer>(gnome100.subList(20, 30));
		String deleteString30a = gnomlistp3a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString30a + "    ");
		ArrayList<Integer> radlistp3a = new ArrayList<Integer>(radix100.subList(20, 30));
		String deleteString28a = radlistp3a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString28a + "    ");
		ArrayList<Integer> coulistp13 = new ArrayList<Integer>(count100.subList(20, 30));
		String deleteString113 = coulistp13.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString113 + "");
		System.out.println();

		ArrayList<Integer> bublistp4a = new ArrayList<Integer>(bubble100.subList(30, 40));
		String deleteString10a = bublistp4a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString10a + "\t ");
		ArrayList<Integer> selclistp4a = new ArrayList<Integer>(selection100.subList(30, 40));
		String deleteString11a = selclistp4a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString11a + "\t  ");
		ArrayList<Integer> inslistp4a = new ArrayList<Integer>(insertion100.subList(30, 40));
		String deleteString12a = inslistp4a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString12a + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp4a = new ArrayList<Integer>(quick100.subList(30, 40));
		String deleteString31a = qlistp4a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString31a + "    ");
		ArrayList<Integer> merglistp4a = new ArrayList<Integer>(merge100.subList(30, 40));
		String deleteString32a = merglistp4a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString32a + "    ");
		ArrayList<Integer> cocklistp4a = new ArrayList<Integer>(cocktail100.subList(30, 40));
		String deleteString34a = cocklistp4a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString34a + "    ");
		ArrayList<Integer> gnomlistp4a = new ArrayList<Integer>(gnome100.subList(30, 40));
		String deleteString35a = gnomlistp4a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString35a + "    ");
		ArrayList<Integer> radlistp4a = new ArrayList<Integer>(radix100.subList(30, 40));
		String deleteString33a = radlistp4a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString33a + "    ");
		ArrayList<Integer> coulistp14 = new ArrayList<Integer>(count100.subList(30, 40));
		String deleteString114 = coulistp14.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString114 + "");
		System.out.println();

		ArrayList<Integer> bublistp5a = new ArrayList<Integer>(bubble100.subList(40, 50));
		String deleteString13a = bublistp5a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString13a + "\t ");
		ArrayList<Integer> selclistp5a = new ArrayList<Integer>(selection100.subList(40, 50));
		String deleteString14a = selclistp5a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString14a + "\t  ");
		ArrayList<Integer> inslistp5a = new ArrayList<Integer>(insertion100.subList(40, 50));
		String deleteString15a = inslistp5a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString15a + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp5a = new ArrayList<Integer>(quick100.subList(40, 50));
		String deleteString36a = qlistp5a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString36a + "    ");
		ArrayList<Integer> merglistp5a = new ArrayList<Integer>(merge100.subList(40, 50));
		String deleteString37a = merglistp5a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString37a + "    ");
		ArrayList<Integer> cocklistp5a = new ArrayList<Integer>(cocktail100.subList(40, 50));
		String deleteString39a = cocklistp5a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString39a + "    ");
		ArrayList<Integer> gnomlistp5a = new ArrayList<Integer>(gnome100.subList(40, 50));
		String deleteString40a = gnomlistp5a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString40a + "    ");
		ArrayList<Integer> radlistp5a = new ArrayList<Integer>(radix100.subList(40, 50));
		String deleteString38a = radlistp5a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString38a + "    ");
		ArrayList<Integer> coulistp15 = new ArrayList<Integer>(count100.subList(40, 50));
		String deleteString115 = coulistp15.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString115 + "");
		System.out.println();

		ArrayList<Integer> bublistp6a = new ArrayList<Integer>(bubble100.subList(50, 60));
		String deleteString41a = bublistp6a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString41a + "\t ");
		ArrayList<Integer> selclistp6a = new ArrayList<Integer>(selection100.subList(50, 60));
		String deleteString42a = selclistp6a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString42a + "\t  ");
		ArrayList<Integer> inslistp6a = new ArrayList<Integer>(insertion100.subList(50, 60));
		String deleteString43a = inslistp6a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString43a + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp6a = new ArrayList<Integer>(quick100.subList(50, 60));
		String deleteString44a = qlistp6a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString44a + "    ");
		ArrayList<Integer> merglistp6a = new ArrayList<Integer>(merge100.subList(50, 60));
		String deleteString45a = merglistp6a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString45a + "    ");
		ArrayList<Integer> cocklistp6a = new ArrayList<Integer>(cocktail100.subList(50, 60));
		String deleteString47a = cocklistp6a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString47a + "    ");
		ArrayList<Integer> gnomlistp6a = new ArrayList<Integer>(gnome100.subList(50, 60));
		String deleteString48a = gnomlistp6a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString48a + "    ");
		ArrayList<Integer> radlistp6a = new ArrayList<Integer>(radix100.subList(50, 60));
		String deleteString46a = radlistp6a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString46a + "    ");
		ArrayList<Integer> coulistp16 = new ArrayList<Integer>(count100.subList(50, 60));
		String deleteString116 = coulistp16.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString116 + "");
		System.out.println();

		ArrayList<Integer> bublistp7a = new ArrayList<Integer>(bubble100.subList(60, 70));
		String deleteString49a = bublistp7a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString49a + "\t ");
		ArrayList<Integer> selclistp7a = new ArrayList<Integer>(selection100.subList(60, 70));
		String deleteString50a = selclistp7a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString50a + "\t  ");
		ArrayList<Integer> inslistp7a = new ArrayList<Integer>(insertion100.subList(60, 70));
		String deleteString51a = inslistp7a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString51a + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp7a = new ArrayList<Integer>(quick100.subList(60, 70));
		String deleteString52a = qlistp7a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString52a + "    ");
		ArrayList<Integer> merglistp7a = new ArrayList<Integer>(merge100.subList(60, 70));
		String deleteString53a = merglistp7a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString53a + "    ");
		ArrayList<Integer> cocklistp7a = new ArrayList<Integer>(cocktail100.subList(60, 70));
		String deleteString55a = cocklistp7a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString55a + "    ");
		ArrayList<Integer> gnomlistp7a = new ArrayList<Integer>(gnome100.subList(60, 70));
		String deleteString56a = gnomlistp7a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString56a + "    ");
		ArrayList<Integer> radlistp7a = new ArrayList<Integer>(radix100.subList(60, 70));
		String deleteString54a = radlistp7a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString54a + "    ");
		ArrayList<Integer> coulistp17 = new ArrayList<Integer>(count100.subList(60, 70));
		String deleteString117 = coulistp17.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString117 + "");
		System.out.println();

		ArrayList<Integer> bublistp8a = new ArrayList<Integer>(bubble100.subList(70, 80));
		String deleteString57a = bublistp8a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString57a + "\t ");
		ArrayList<Integer> selclistp8a = new ArrayList<Integer>(selection100.subList(70, 80));
		String deleteString58a = selclistp8a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString58a + "\t  ");
		ArrayList<Integer> inslistp8a = new ArrayList<Integer>(insertion100.subList(70, 80));
		String deleteString59a = inslistp8a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString59a + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp8a = new ArrayList<Integer>(quick100.subList(70, 80));
		String deleteString60a = qlistp8a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString60a + "    ");
		ArrayList<Integer> merglistp8a = new ArrayList<Integer>(merge100.subList(70, 80));
		String deleteString61a = merglistp8a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString61a + "    ");
		ArrayList<Integer> cocklistp8a = new ArrayList<Integer>(cocktail100.subList(70, 80));
		String deleteString63a = cocklistp8a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString63a + "    ");
		ArrayList<Integer> gnomlistp8a = new ArrayList<Integer>(gnome100.subList(70, 80));
		String deleteString64a = gnomlistp8a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString64a + "    ");
		ArrayList<Integer> radlistp8a = new ArrayList<Integer>(radix100.subList(70, 80));
		String deleteString62a = radlistp8a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString62a + "    ");
		ArrayList<Integer> coulistp18 = new ArrayList<Integer>(count100.subList(70, 80));
		String deleteString118 = coulistp18.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString118 + "");
		System.out.println();

		ArrayList<Integer> bublistp9a = new ArrayList<Integer>(bubble100.subList(80, 90));
		String deleteString65a = bublistp9a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString65a + "\t ");
		ArrayList<Integer> selclistp9a = new ArrayList<Integer>(selection100.subList(80, 90));
		String deleteString66a = selclistp9a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString66a + "\t  ");
		ArrayList<Integer> inslistp9a = new ArrayList<Integer>(insertion100.subList(80, 90));
		String deleteString67a = inslistp9a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString67a + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp9a = new ArrayList<Integer>(quick100.subList(80, 90));
		String deleteString68a = qlistp9a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString68a + "    ");
		ArrayList<Integer> merglistp9a = new ArrayList<Integer>(merge100.subList(80, 90));
		String deleteString69a = merglistp9a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString69a + "    ");
		ArrayList<Integer> cocklistp9a = new ArrayList<Integer>(cocktail100.subList(80, 90));
		String deleteString71a = cocklistp9a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString71a + "    ");
		ArrayList<Integer> gnomlistp9a = new ArrayList<Integer>(gnome100.subList(80, 90));
		String deleteString72a = gnomlistp9a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString72a + "    ");
		ArrayList<Integer> radlistp9a = new ArrayList<Integer>(radix100.subList(80, 90));
		String deleteString70a = radlistp9a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString70a + "    ");
		ArrayList<Integer> coulistp19 = new ArrayList<Integer>(count100.subList(80, 90));
		String deleteString119 = coulistp19.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString119 + "");
		System.out.println();

		ArrayList<Integer> bublistp10a = new ArrayList<Integer>(bubble100.subList(90, 100));
		String deleteString73a = bublistp10a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString73a + "\t ");
		ArrayList<Integer> selclistp10a = new ArrayList<Integer>(selection100.subList(90, 100));
		String deleteString74a = selclistp10a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString74a + "\t  ");
		ArrayList<Integer> inslistp10a = new ArrayList<Integer>(insertion100.subList(90, 100));
		String deleteString75a = inslistp10a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString75a + "\t   ");
		//System.out.println();
		ArrayList<Integer> qlistp10a = new ArrayList<Integer>(quick100.subList(90, 100));
		String deleteString76a = qlistp10a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString76a + "    ");
		ArrayList<Integer> merglistp10a = new ArrayList<Integer>(merge100.subList(90, 100));
		String deleteString77a = merglistp10a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString77a + "    ");
		ArrayList<Integer> cocklistp10a = new ArrayList<Integer>(cocktail100.subList(90, 100));
		String deleteString79a = cocklistp10a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString79a + "    ");
		ArrayList<Integer> gnomlistp10a = new ArrayList<Integer>(gnome100.subList(90, 100));
		String deleteString80a = gnomlistp10a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString80a + "    ");
		ArrayList<Integer> radlistp10a = new ArrayList<Integer>(radix100.subList(90, 100));
		String deleteString78a = radlistp10a.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString78a + "    ");
		ArrayList<Integer> coulistp20 = new ArrayList<Integer>(count100.subList(90, 100));
		String deleteString120 = coulistp20.toString().replace(",", "").replace("[", "").replace("]", "").trim();
		System.out.print(deleteString120 + "");
		System.out.println();
		System.out.println();
		
		bs.compare();
		System.out.printf(" ");
		sc.compare();
		System.out.printf("\t\t  ");
		ins.compare();
		System.out.printf("\t\t   ");
		QuickSort.compare();
		System.out.printf("\t\t    ");
		MergeSort.compare();
		System.out.printf("\t\t     ");
		//RadixSort.compare();
		CockTailSort.compare();
		System.out.printf("\t      ");
		GnomeSort.compare();
		System.out.printf("\t       ");
		RadixSort.runtime();
		System.out.printf("\t\t\t");
		ins.runtime();
		System.out.println();
		bs.swap();
		System.out.printf("\t\t\t ");
		sc.swap();
		System.out.printf("\t\t\t  ");
		ins.swap();
		System.out.printf("\t\t\t   ");
		QuickSort.swap();
		System.out.printf("\t\t\t    ");
		MergeSort.swap();
		System.out.printf(" ");
		//RadixSort.swap();
		System.out.printf("\t\t\t     ");
		CockTailSort.swap(); 
		System.out.printf("\t\t      ");
		GnomeSort.swap();
		System.out.printf("\t\t\t  ");
		System.out.println();
		
		bs.runtime(); 
		System.out.printf("\t\t\t ");
		sc.runtime();
		System.out.printf("\t\t\t  ");
		ins.runtime();
		System.out.printf("\t\t\t   ");
		qui.runtime();
		System.out.printf("\t\t    ");
		MergeSort.runtime();
		System.out.printf("\t     ");
		System.out.printf("\t     ");
		CockTailSort.runtime();
		System.out.printf("\t\t      ");
		GnomeSort.runtime();
		System.out.printf("\t\t\t  ");
		System.out.println();
		System.out.println();

	}	
	public static void print1kList() {
		ArrayList<Integer> list17 = new ArrayList<Integer>();
		RandomIntegers.randomizeList1k(list17);		
		
		ArrayList<Integer> bubble1k = bs.print(list17);
		ArrayList<Integer> selection1k = sc.print(list17);
		ArrayList<Integer> insertion1k = ins.print(list17);
		ArrayList<Integer> quick1k = qui.print(list17);
		ArrayList<Integer> merge1k = mer.print(list17);
		ArrayList<Integer> cocktail1k = cock.print(list17);
		ArrayList<Integer> gnome1k = gno.print(list17);
		ArrayList<Integer> radix1k = rad.print(list17);
		ArrayList<Integer> count1k = coun.print(list17);
		
		int[] countk = new int[count1k.size()];
		for (int i = 0; i < countk.length; i++) {
			countk[i] = count1k.get(i);
		}bs.bubbleSort(count1k);

		System.out.println();
		System.out.print("1000 Elements\t\t\t 1000 Elements\t\t\t  1000 Elements\t\t\t   1000 Elements\t\t    1000 Elements\t\t     1000 Elements\t\t      1000 Elements\t\t       1000 Elements\t\t        1000 Elements");
		
		bs.bubbleSort(bubble1k);
		sc.selectionSort(selection1k);
		ins.insertionSort(insertion1k);
		qui.quickSort4(quick1k);
		mer.mergeSort3(merge1k);
		cock.cockTailSort(cocktail1k);
		gno.gnomeSort(gnome1k);
		rad.radixSort(radix1k);
		coun.countingSort(countk);
		
		System.out.println();
		System.out.println("Bubble sorted 1k stats:\t\t Selection sorted 1k stats:\t  Insertion sorted 1k stats:\t   Quick sorted 1k stats:\t    Merge sorted 1k stats:\t     Cocktail sorted 1k stats:\t      Gnome sorted 1k stats:\t       Radix sort 1k stats:\t        Counting sorted 1k stats:");
		
		bs.compare();
		System.out.printf(" ");
		sc.compare();
		System.out.printf("\t\t  ");
		ins.compare();
		System.out.printf("\t\t   ");
		QuickSort.compare();
		System.out.printf("\t\t    ");
		MergeSort.compare();
		System.out.printf("\t\t     ");
		CockTailSort.compare();
		System.out.printf("      ");
		GnomeSort.compare();
		System.out.printf("       ");
		RadixSort.runtime();
		System.out.printf("       \t\t");
		qui.runtime();
		System.out.println();
		
		bs.swap();
		System.out.printf("\t\t\t ");
		sc.swap();
		System.out.printf("\t\t\t  ");
		ins.swap();
		System.out.printf("\t\t\t   ");
		QuickSort.swap();
		System.out.printf("\t\t\t    ");
		MergeSort.swap();
		System.out.printf("\t ");
		System.out.printf("\t\t     ");
		CockTailSort.swap();
		System.out.printf("\t\t      ");
		GnomeSort.swap();
		System.out.printf("\t\t\t  ");
		System.out.println();
		
		bs.runtime();
		System.out.printf("\t\t\t ");
		sc.runtime();
		System.out.printf("\t\t\t  ");
		ins.runtime();
		System.out.printf("\t\t   ");
		qui.runtime();
		System.out.printf("\t\t    ");
		MergeSort.runtime();
		System.out.printf("\t     ");

		System.out.printf("\t     ");
		CockTailSort.runtime();
		System.out.printf("\t\t      ");
		GnomeSort.runtime();
		System.out.printf("\t\t\t  ");
		System.out.println();
	}
	public static void print10kList() {
		ArrayList<Integer> list25 = new ArrayList<Integer>();
		RandomIntegers.randomizeList10k(list25);
		
		ArrayList<Integer> bubble10k = bs.print(list25);
		ArrayList<Integer> selection10k = sc.print(list25);
		ArrayList<Integer> insertion10k = ins.print(list25);
		ArrayList<Integer> quick10k = qui.print(list25);
		ArrayList<Integer> merge10k = mer.print(list25);
		ArrayList<Integer> cocktail10k = cock.print(list25);
		ArrayList<Integer> gnome10k = gno.print(list25);
		ArrayList<Integer> radix10k = rad.print(list25);
		ArrayList<Integer> count10k = coun.print(list25);
		
		int[] count0k = new int[count10k.size()];
		for (int i = 0; i < count0k.length; i++) {
			count0k[i] = count10k.get(i);
		}bs.bubbleSort(count10k);

		System.out.println();
		System.out.println();
		
		System.out.print("10k Elements\t\t\t 10k Elements\t\t\t  10k Elements\t\t\t   10k Elements\t\t\t    10k Elements\t\t     10k Elements\t\t      10k Elements\t\t       10k Elements\t\t\t10k Elements");
		
		bs.bubbleSort(bubble10k);
		sc.selectionSort(selection10k);
		ins.insertionSort(insertion10k);
		qui.quickSort4(quick10k);
		mer.mergeSort3(merge10k);
		rad.radixSort(radix10k);
		cock.cockTailSort(cocktail10k);
		gno.gnomeSort(gnome10k);
		coun.countingSort(count0k);
		
		System.out.println();
		System.out.println("Bubble sorted 10k stats:\t Selection sorted 10k stats:\t  Insertion sorted 10k stats:\t   Quick sorted 10k stats:\t    Merge sorted 10k stats:\t     Cocktail sorted 10k stats:\t      Gnome sorted 10k stats:\t       Radix sort 10k stats:\t\tCounting sorted 10k stats:");

		bs.compare();
		System.out.printf(" ");
		sc.compare();
		System.out.printf("\t\t  ");
		ins.compare();
		System.out.printf("\t\t   ");
		QuickSort.compare();
		System.out.printf("\t\t    ");
		MergeSort.compare();
		System.out.printf("\t             ");
		//	RadixSort.compare();
		CockTailSort.compare();
		System.out.printf("      ");
		GnomeSort.compare();
		System.out.printf("       ");
		RadixSort.runtime();
		System.out.printf("      \t\t");
		MergeSort.euntime();
		System.out.println();
		
		bs.swap();
		System.out.printf("\t\t\t ");
		sc.swap();
		System.out.printf("\t\t\t  ");
		ins.swap();
		System.out.printf("\t\t\t   ");
		QuickSort.swap();
		System.out.printf("\t\t\t    ");
		MergeSort.swap();
		System.out.printf("\t     ");
		//RadixSort.swap();
		System.out.printf("\t\t     ");
		CockTailSort.swap();
		System.out.printf("\t\t      ");
		GnomeSort.swap();
		System.out.printf("\t\t\t  ");
		System.out.println();
		
		bs.runtime();
		System.out.printf("\t\t\t ");
		sc.runtime();
		System.out.printf("\t\t  ");
		ins.runtime();
		System.out.printf("\t\t   ");
		qui.runtime();
		System.out.printf("\t\t    ");
		MergeSort.runtime();
		System.out.printf("\t ");

		System.out.printf("\t     ");
		CockTailSort.runtime();
		System.out.printf("\t\t      ");
		GnomeSort.runtime();
		System.out.printf("\t\t\t  ");
		System.out.println();
	}
	public static void print100kList() {
		ArrayList<Integer> list33 = new ArrayList<Integer>();
		RandomIntegers.randomizeList100k(list33);
		
		ArrayList<Integer> bubble100k = bs.print(list33);
		ArrayList<Integer> selection100k = sc.print(list33);
		ArrayList<Integer> insertion100k = ins.print(list33);
		ArrayList<Integer> quick100k = qui.print(list33);
		ArrayList<Integer> merge100k = mer.print(list33);
		ArrayList<Integer> cocktail100k = cock.print(list33);
		ArrayList<Integer> gnome100k = gno.print(list33);
		ArrayList<Integer> radix100k = rad.print(list33);
		ArrayList<Integer> count100k = coun.print(list33);
		
		int[] count00k = new int[count100k.size()];
		for (int i = 0; i < count00k.length; i++) {
			count00k[i] = count100k.get(i);
		}

		System.out.println();
		System.out.println();
		System.out.print("100k Elements\t\t\t 100k Elements\t\t\t  100k Elements\t\t\t   100k Elements\t\t    100k Elements\t\t     100k Elements\t\t      100k Elements\t\t       100k Elements\t\t       100k Elements");
		System.out.println();
		System.out.println("Bubble sorted 100k stats:\t Selection sorted 100k stats:\t  Insertion sorted 100k stats:\t   Quick sorted 100k stats:\t    Merge sorted 100k stats:\t     Cocktail sorted 100k stats:      Gnome sorted 100k stats:\t       Radix sort 100k stats:\t       Counting sort 100k stats:");
	
		bs.bubbleSort(count100k);
		bs.bubbleSort(bubble100k);
		bs.compare();
		System.out.printf(" ");
		sc.selectionSort(selection100k);
		sc.compare();
		System.out.printf("\t  ");
		ins.insertionSort(insertion100k);
		ins.compare();
		System.out.printf("\t   ");
		qui.quickSort4(quick100k);
		QuickSort.compare();
		System.out.printf("\t\t    ");
		mer.mergeSort3(merge100k);
		MergeSort.compare();
		System.out.printf("\t\t     ");
		cock.cockTailSort(cocktail100k);
		CockTailSort.compare();
		System.out.printf("      ");
		gno.gnomeSort(gnome100k);
		GnomeSort.compare();
		System.out.printf("       ");
		rad.radixSort(radix100k);
		RadixSort.runtime();
	    System.out.printf("\t\t       ");
	    coun.countingSort(count00k);
		qui.euntime();
		System.out.println();
		
		bs.swap();
		System.out.printf("\t\t ");
		sc.swap();
		System.out.printf("\t\t          ");
		ins.swap();
		System.out.printf("\t\t\t   ");
		QuickSort.swap();
		System.out.printf("\t\t    ");
		MergeSort.swap();
		System.out.printf("\t\t ");
		System.out.printf("\t     ");
		CockTailSort.swap();
		System.out.printf("\t\t      ");
		GnomeSort.swap();
		System.out.printf("\t\t\t  ");
		System.out.println();
	
		bs.runtime();
		System.out.printf("\t\t ");
		sc.runtime();
		System.out.printf("\t          ");
		ins.runtime();
		System.out.printf("\t\t   ");
		qui.runtime();
		System.out.printf("\t\t    ");
		MergeSort.runtime();
		System.out.printf("\t ");

		System.out.printf("\t     ");
		CockTailSort.runtime();
		System.out.printf("\t\t      ");
		GnomeSort.runtime();
		System.out.printf("\t\t\t  ");
	}
}